config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :flights
  resources :bookings
   #root "flights#index" 
end

app/models/airport.rb
class Airport < ApplicationRecord
    has_many :departing_flights, class_name: "Flight", foreign_key: "departure_airport_id"
    has_many :arriving_flights, class_name: "Flight", foreign_key: "arrival_airport_id"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengerbookings, dependent: :delete_all 
  has_many :passengers, through: :passengerbookings, inverse_of: :bookings
  
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
    belongs_to  :departure_airport, class_name: "Airport", foreign_key: "departure_airport_id"
    belongs_to :arrival_airport, class_name: "Airport", foreign_key: "arrival_airport_id"
    has_many :bookings
    has_many :passengers, through: :bookings
end

app/models/passenger.rb
class Passenger < ApplicationRecord
    has_many :passengerbookings, dependent: :delete_all 
    has_many :bookings, through: :passengerbookings, inverse_of: :passengers 
    has_many :flights, through: :bookings
end

app/models/passengerbooking.rb
class Passengerbooking < ApplicationRecord
  belongs_to :passenger
  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

    def new 
        @booking = Booking.new 
        # params[:passengers].to_i.times {@booking.passengers.build}
        params[:passengers].to_i.times {@booking.passengers.build}
        @flight = Flight.find(params[:flight_id])
        render :new
    end 

    def create 
        @booking = Booking.new(booking_params)
        

        if @booking.save 
            flash.notice ="Vuelo reservado"
            redirect_to @booking
        else 
            redirect_to new_flight_path
        end  
    end 

    def show 

        @booking = Booking.find(params[:id])

        @n = 1
    end 

    def edit 
        @booking = Booking.find(params[:id])
        
    end 

    private 

    def booking_params
        params.require(:booking).permit(:flight_id, passengers_attributes: [:id, :name, :email])
    end 

end 

app/controllers/flights_controller.rb
class FlightsController < ApplicationController 

    def index
      @flights = Flight.all
      @airport_options = Airport.all.map {|a| [a.code, a.id]}
      @flight_selected = Flight.find_by(scheduled_on: params[:date])

      @available_flight = Flight.where(arrival_airport_id: params[:arrival_airport_id], departure_airport_id: params[:departure_airport_id], 
        scheduled_on: params[:date])
      
    end 

    def show 
      @flight = Flight.find(params[:id])
    end 

    def new 
      @flight = Flight.new
      @airport_options = Airport.all.map {|a| [a.code, a.id]}
    end 

    def create 
      @flight = Flight.new(flight_params)
      @airport_options = Airport.all.map {|a| [a.code, a.id]}
      respond_to do |format|
        if @flight.save
        format.html { redirect_to flight_path(@flight), notice: "Flight was successfully created." }
      else 
         format.html { render :new, status: :unprocessable_entity }
      end 
    end 

    end 

    private 
    
    def flight_params 
      params.require(:flight).permit(:departure_airport_id, :arrival_airport_id, :scheduled_on, :duration, :commit, :authenticity_token)
    end 

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= form_with(model: @booking) do |f| %>

    
    <%= f.hidden_field :flight_id, value: @flight.id %>

    <div>
        <%= f.fields_for :passengers do |passengers_form| %>
        <br>
        <%= passengers_form.label :Nombre_pasajero %>
        <%= passengers_form.text_field :name %>
        <br>
        <%= passengers_form.label :Mail %>
        <%= passengers_form.text_field :email %>
        <% end %>
    </div>

    <div>
        <%= f.submit "Submit" %>
    </div>

<% end %>

app/views/bookings/edit.html.erb
Edición

<%= @booking.flight.name %>

app/views/bookings/new.html.erb
<div>

    <h2>Datos sobre la reserva:</h2>

    <p>El vuelo parte desde: <%= @flight.departure_airport.code %></p>
    
    <p>Hasta: <%= @flight.arrival_airport.code %></p>
     
    <p>En la fecha de: <%= @flight.scheduled_on %></p>
     
    <p>Número de pasajes a reservar: <%= params[:passengers] %></p>
    
</div>

<div>
    <h2>Información sobre los pasajeros</h2>
    <%= render 'form' %>
</div>

app/views/bookings/show.html.erb
<div>
    <h2>Detalles sobre la reserva</h2>

   <% @booking.passengers.each_with_index do |passenger, idx| %>   
        <h3>Pasajero <%= @n %></h3>
        <p>Nombre: <%= passenger.name %></p>
        <p>Email: <%= passenger.name %></p>
        <% @n += 1 %>
      <% end %>
    
    <h3>Vuelo</h3>
    <p><%= @booking.flight.departure_airport.code %></p>
    <p><%= @booking.flight.arrival_airport.code %></p>
    <p><%= @booking.flight.scheduled_on %></p>
    
    <%= link_to "Editar reserva", edit_booking_path, method: :get %>
    <%= button_to "Reservar otro vuelo", flights_path, method: :get %>
</div>

app/views/flights/_form.html.erb
<%= form_with(model: @flight) do |form| %>


  <div>
    <%= form.label :scheduled_on, style: "display: block" %>
    <%= form.date_field :scheduled_on %>
  </div>

  <div>
    <%= form.label :departure_airport_id, style: "display: block" %>
    <%= form.number_field :departure_airport_id %>
  </div>

  <div>
    <%= form.label :arrival_airport_id, style: "display: block" %>
    <%= form.number_field :arrival_airport_id %>
  </div>

  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.number_field :duration %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/flights/_show.html.erb
<% @flights.each do |f| %>
<%= f.id %> <br>
<%= f.scheduled_on %>
<% end %>

app/views/flights/index.html.erb
<%= form_with url: "/flights", method: :get do |form| %>

    <%= form.label :departure_airport %>
    <%= select_tag(:departure_airport_id, options_for_select(@airport_options, selected: params[:departure_airport_id])) %> <br>

    <%= form.label :arrival_airport %>
    <%= select_tag(:arrival_airport_id, options_for_select(@airport_options, selected: params[:arrival_airport_id])) %> <br>
  
    <%= form.label :date %>
    <%= form.date_field :date %> <br>

    <%= form.label :passengers %>
    <%= form.select :passengers, (1..4) %> <br>

    <%= form.submit %> 
<% end %>

<% unless  @available_flight.nil? %>
    <% if @available_flight.any? %>

    <div>El vuelo sale desde:</div>
    <%= Airport.find(params[:departure_airport_id]).code %>
    <div>Destino a:</div>
    <%= Airport.find(params[:arrival_airport_id]).code %>
    <div>Fecha de salida:</div>
    <%= @flight_selected.scheduled_on %>
    <div>Pasajes a sacar:</div>
    <%= params[:passengers] %>


<div>
    <%= button_to 'Book flight', new_booking_path, method: :get, params: {flight_id: @flight_selected.id, passengers: params[:passengers]} %>
</div>

    <% end %>
<% end %>

<br>

<%= link_to "form", new_flight_path %> <br>

<%= render 'show' %>

app/views/flights/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  
    <%= flash[:notice] %>
       <%= flash[:alert] %>
     
    <%= yield %>
  </body>
</html>